### PR TITLE
Allow connecting to c-lightning over TCP

### PR DESCRIPTION
**Pull request by Desuuuu**
Allows connecting to c-lightning over TCP when a valid port is passed as the 2nd argument to LightningClient's constructor.

### CODE REVIEW

**Comment by shesek** [comment]
C-lightning does not natively support TCP connections. It is possible to use something like `socat` to expose the unix socket over TCP (like c-lightning's docker image [does](https://github.com/ElementsProject/lightning/blob/7635b24a29e274a9e85cf9a8c963d364fa3fadec/tools/docker-entrypoint.sh#L15)), but this is not recommended in a production environment because c-lightning has no authentication mechanism (c-lightning's [docs](https://github.com/ElementsProject/lightning#installation) describe `EXPOSE_TCP` as "Use only for testing").

So, I'm somewhat worried that supporting this could end up being a footgun. May I ask why you're exposing it over TCP?

Could an SSH tunnel forwarding the UNIX socket work for your use case? This would leverage SSH's authentication mechanism and be more secure. Something like ```$ ssh -nNT -L `pwd`/lightning-rpc:/home/user/.lightning/lightning-rpc user@host```, then treating `./lightning-rpc` like you would a regular UNIX socket. To make the tunnel permanent, you can look into using `autossh`.

**Comment by Desuuuu** [comment]
I'm effectively running c-lightning in a Docker environment and my RPC is exposed to my host machine using socat.

The reason behind this is that I like containers but I prefer them lightweight and separated ; right now I'm going to try the web interface from your Spark Wallet (looks great by the way!) however I do not want to add it to my c-lightning container. I'd much rather run it in its own container and link the two containers together.

I can understand why you're concerned about this in a remote scenario (which is not my case). I still feel like this could be useful and good in terms of flexibility.

Obviously this is already possible by using, for example, socat on both sides (spark<->socat1<-(TCP)->socat2<->clightning) but I find it superfluous to have to run extra software when the code can give the option to connect over TCP ; I would rather let people take care of security and maybe put up a warning that this *could* be insecure in some scenarios.

**Comment by shesek** [comment]
If its meant for a docker-compose setup where everything is run on the same machine, why not mount the lightning data directory (and the unix socket in it) to both containers?

Something like this should work (not actually tested, just for the general idea):

```
version: "3"
services:
  bitcoind:
    image: nicolasdorier/docker-bitcoin:0.16.0
    container_name: bitcoind
    environment: ...
    expose:
      - "18332"
    volumes:
      - "bitcoin_datadir:/data"

  clightning_bitcoin:
    image: elementsproject/lightningd
    container_name: lightningd
    command: ...
    environment: ...
    expose:
      - "9735"
    volumes:
      - "clightning_bitcoin_datadir:/root/.lightning"
      - "bitcoin_datadir:/etc/bitcoin"
    links:
      - bitcoind

  spark:
    image: shesek/spark-wallet
    container_name: spark
    command: ...
    environment: ...
    expose:
      - "9737"
    volumes:
      - "clightning_bitcoin_datadir:/etc/lightning"
      - "spark_datadir:/data"
    links:
      - clightning_bitcoin

volumes:
  bitcoin_datadir:
  clightning_bitcoin_datadir:
  spark_datadir:
```

**Comment by shesek** [comment]
You can also mount a directory from your host into the c-lightning container's `/root/.lightning`, which will make the UNIX socket available on your host.

**Comment by shesek** [comment]
Also see: https://github.com/shesek/spark-wallet/blob/login-file/doc/docker.md#with-existing-lightningd

@Desuuuu would you still prefer to use TCP?

**Comment by Desuuuu** [comment]
Thanks for the advice!

I still went with TCP, I prefer this over sharing c-lightning's root directory. It feels slightly more secure to me, since this directory also contains my hsm_secret file.

I guess you could work around this by configuring c-lightning to put the rpc socket in another directory and share this directory with Spark's container instead. Since it works fine for me already with TCP, I don't plan on trying this though!

**Comment by shesek** [comment]
You could use `-v /path/on/host/lightning/lightning-rpc:/etc/lightning/lightning-rpc` to mount just the unix socket to the Spark container and not anything else, but it seems like [there's no](https://github.com/moby/moby/issues/32582) equivalent to doing that with named volumes in a docker-compose setup. But you could use two separate named volumes and set `--rpc-file` to the second one, like you suggested.

Overall, I think that supporting TCP without some form of authentication mechanism is too dangerous. It's not a matter of "could be insecure in some scenarios", but rather something that is "insecure by default when used out-of-the-box as-is, unless you take extra unspecified steps (firewall etc) that aren't natively implemented".

This can be reconsidered if/when c-lightning adds authentication.

**Pull request closed without merging**
